// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primtypes.djinni

#pragma once

#include <cstdint>
#include <experimental/optional>
#include <utility>

struct AssortedPrimitives final {
    bool b;
    int8_t eight;
    int16_t sixteen;
    int32_t thirtytwo;
    int64_t sixtyfour;
    float fthirtytwo;
    double fsixtyfour;
    std::experimental::optional<bool> o_b;
    std::experimental::optional<int8_t> o_eight;
    std::experimental::optional<int16_t> o_sixteen;
    std::experimental::optional<int32_t> o_thirtytwo;
    std::experimental::optional<int64_t> o_sixtyfour;
    std::experimental::optional<float> o_fthirtytwo;
    std::experimental::optional<double> o_fsixtyfour;

    friend bool operator==(const AssortedPrimitives& lhs, const AssortedPrimitives& rhs);
    friend bool operator!=(const AssortedPrimitives& lhs, const AssortedPrimitives& rhs);

    AssortedPrimitives(bool _b,
                       int8_t _eight,
                       int16_t _sixteen,
                       int32_t _thirtytwo,
                       int64_t _sixtyfour,
                       float _fthirtytwo,
                       double _fsixtyfour,
                       std::experimental::optional<bool> _o_b,
                       std::experimental::optional<int8_t> _o_eight,
                       std::experimental::optional<int16_t> _o_sixteen,
                       std::experimental::optional<int32_t> _o_thirtytwo,
                       std::experimental::optional<int64_t> _o_sixtyfour,
                       std::experimental::optional<float> _o_fthirtytwo,
                       std::experimental::optional<double> _o_fsixtyfour)
    : b(std::move(_b))
    , eight(std::move(_eight))
    , sixteen(std::move(_sixteen))
    , thirtytwo(std::move(_thirtytwo))
    , sixtyfour(std::move(_sixtyfour))
    , fthirtytwo(std::move(_fthirtytwo))
    , fsixtyfour(std::move(_fsixtyfour))
    , o_b(std::move(_o_b))
    , o_eight(std::move(_o_eight))
    , o_sixteen(std::move(_o_sixteen))
    , o_thirtytwo(std::move(_o_thirtytwo))
    , o_sixtyfour(std::move(_o_sixtyfour))
    , o_fthirtytwo(std::move(_o_fthirtytwo))
    , o_fsixtyfour(std::move(_o_fsixtyfour))
    {}
};
