// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primtypes.djinni

#pragma once

#include <cstdint>
#include <experimental/optional>
#include <utility>

namespace testsuite {

struct AssortedPrimitives final {
    bool b;
    int8_t eight;
    int16_t sixteen;
    int32_t thirtytwo;
    int64_t sixtyfour;
    float fthirtytwo;
    double fsixtyfour;
    std::experimental::optional<bool> o_b;
    std::experimental::optional<int8_t> o_eight;
    std::experimental::optional<int16_t> o_sixteen;
    std::experimental::optional<int32_t> o_thirtytwo;
    std::experimental::optional<int64_t> o_sixtyfour;
    std::experimental::optional<float> o_fthirtytwo;
    std::experimental::optional<double> o_fsixtyfour;

    friend bool operator==(const AssortedPrimitives& lhs, const AssortedPrimitives& rhs);
    friend bool operator!=(const AssortedPrimitives& lhs, const AssortedPrimitives& rhs);

    AssortedPrimitives(bool new_b,
                       int8_t new_eight,
                       int16_t new_sixteen,
                       int32_t new_thirtytwo,
                       int64_t new_sixtyfour,
                       float new_fthirtytwo,
                       double new_fsixtyfour,
                       std::experimental::optional<bool> new_o_b,
                       std::experimental::optional<int8_t> new_o_eight,
                       std::experimental::optional<int16_t> new_o_sixteen,
                       std::experimental::optional<int32_t> new_o_thirtytwo,
                       std::experimental::optional<int64_t> new_o_sixtyfour,
                       std::experimental::optional<float> new_o_fthirtytwo,
                       std::experimental::optional<double> new_o_fsixtyfour)
    : b(std::move(new_b))
    , eight(std::move(new_eight))
    , sixteen(std::move(new_sixteen))
    , thirtytwo(std::move(new_thirtytwo))
    , sixtyfour(std::move(new_sixtyfour))
    , fthirtytwo(std::move(new_fthirtytwo))
    , fsixtyfour(std::move(new_fsixtyfour))
    , o_b(std::move(new_o_b))
    , o_eight(std::move(new_o_eight))
    , o_sixteen(std::move(new_o_sixteen))
    , o_thirtytwo(std::move(new_o_thirtytwo))
    , o_sixtyfour(std::move(new_o_sixtyfour))
    , o_fthirtytwo(std::move(new_o_fthirtytwo))
    , o_fsixtyfour(std::move(new_o_fsixtyfour))
    {}
};

}  // namespace testsuite
