// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include <cstdint>
#include <experimental/optional>
#include <string>
#include <utility>

struct ClientReturnedRecord final {
    int64_t record_id;
    std::string content;
    std::experimental::optional<std::string> misc;

    ClientReturnedRecord(int64_t new_record_id,
                         std::string new_content,
                         std::experimental::optional<std::string> new_misc)
    : record_id(std::move(new_record_id))
    , content(std::move(new_content))
    , misc(std::move(new_misc))
    {}
};
