// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from client_interface.djinni

#pragma once

#include <cstdint>
#include <experimental/optional>
#include <string>
#include <utility>

struct ClientReturnedRecord final {
    int64_t record_id;
    std::string content;
    std::experimental::optional<std::string> misc;

    ClientReturnedRecord(int64_t _record_id,
                         std::string _content,
                         std::experimental::optional<std::string> _misc)
    : record_id(std::move(_record_id))
    , content(std::move(_content))
    , misc(std::move(_misc))
    {}
};
