// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#pragma once

#include <chrono>
#include <utility>

struct DateRecord final {
    std::chrono::system_clock::time_point created_at;

    friend bool operator==(const DateRecord& lhs, const DateRecord& rhs);
    friend bool operator!=(const DateRecord& lhs, const DateRecord& rhs);

    friend bool operator<(const DateRecord& lhs, const DateRecord& rhs);
    friend bool operator>(const DateRecord& lhs, const DateRecord& rhs);

    friend bool operator<=(const DateRecord& lhs, const DateRecord& rhs);
    friend bool operator>=(const DateRecord& lhs, const DateRecord& rhs);

    DateRecord(std::chrono::system_clock::time_point new_created_at)
    : created_at(std::move(new_created_at))
    {}
};
