// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#pragma once

#include "color.hpp"
#include "record_with_derivings.hpp"
#include <utility>

/** This file tests YAML dumped by Djinni can be parsed back in */
struct ExternRecordWithDerivings final {
    ::RecordWithDerivings member;
    ::color e;

    friend bool operator==(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);
    friend bool operator!=(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);

    friend bool operator<(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);
    friend bool operator>(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);

    friend bool operator<=(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);
    friend bool operator>=(const ExternRecordWithDerivings& lhs, const ExternRecordWithDerivings& rhs);

    ExternRecordWithDerivings(::RecordWithDerivings new_member,
                              ::color new_e)
    : member(std::move(new_member))
    , e(std::move(new_e))
    {}
};
