// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#pragma once

#include <cstdint>
#include <string>
#include <unordered_map>
#include <utility>

namespace testsuite {

struct MapRecord final {
    std::unordered_map<std::string, int64_t> map;
    std::unordered_map<int32_t, int32_t> imap;

    MapRecord(std::unordered_map<std::string, int64_t> new_map,
              std::unordered_map<int32_t, int32_t> new_imap)
    : map(std::move(new_map))
    , imap(std::move(new_imap))
    {}
};

}  // namespace testsuite
