// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primitive_list.djinni

#pragma once

#include <cstdint>
#include <utility>
#include <vector>

namespace testsuite {

struct PrimitiveList final {
    std::vector<int64_t> list;

    PrimitiveList(std::vector<int64_t> new_list)
    : list(std::move(new_list))
    {}
};

}  // namespace testsuite
