// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from derivings.djinni

#pragma once

#include "record_with_derivings.hpp"
#include <cstdint>
#include <utility>

struct RecordWithNestedDerivings final {
    int32_t key;
    RecordWithDerivings rec;

    friend bool operator==(const RecordWithNestedDerivings& lhs, const RecordWithNestedDerivings& rhs);
    friend bool operator!=(const RecordWithNestedDerivings& lhs, const RecordWithNestedDerivings& rhs);

    friend bool operator<(const RecordWithNestedDerivings& lhs, const RecordWithNestedDerivings& rhs);
    friend bool operator>(const RecordWithNestedDerivings& lhs, const RecordWithNestedDerivings& rhs);

    friend bool operator<=(const RecordWithNestedDerivings& lhs, const RecordWithNestedDerivings& rhs);
    friend bool operator>=(const RecordWithNestedDerivings& lhs, const RecordWithNestedDerivings& rhs);

    RecordWithNestedDerivings(int32_t new_key,
                              RecordWithDerivings new_rec)
    : key(std::move(new_key))
    , rec(std::move(new_rec))
    {}
};
