// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from set.djinni

#pragma once

#include <cstdint>
#include <string>
#include <unordered_set>
#include <utility>

struct SetRecord final {
    std::unordered_set<std::string> set;
    std::unordered_set<int32_t> iset;

    SetRecord(std::unordered_set<std::string> new_set,
              std::unordered_set<int32_t> new_iset)
    : set(std::move(new_set))
    , iset(std::move(new_iset))
    {}
};
